# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Sat Oct  7 13:56:54 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1353, 727)
        self.c = QtGui.QWidget(MainWindow)
        self.c.setObjectName("c")
        self.gridLayout = QtGui.QGridLayout(self.c)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 5, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fr_face_container = QtGui.QFrame(self.c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr_face_container.sizePolicy().hasHeightForWidth())
        self.fr_face_container.setSizePolicy(sizePolicy)
        self.fr_face_container.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_face_container.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_face_container.setObjectName("fr_face_container")
        self.gridLayout_2 = QtGui.QGridLayout(self.fr_face_container)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(257, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.fr_face_stream = QtGui.QFrame(self.fr_face_container)
        self.fr_face_stream.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_face_stream.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_face_stream.setObjectName("fr_face_stream")
        self.gridLayout_3 = QtGui.QGridLayout(self.fr_face_stream)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gv_face_stream = QtGui.QGraphicsView(self.fr_face_stream)
        self.gv_face_stream.setMinimumSize(QtCore.QSize(800, 600))
        self.gv_face_stream.setMaximumSize(QtCore.QSize(800, 600))
        self.gv_face_stream.setObjectName("gv_face_stream")
        self.gridLayout_3.addWidget(self.gv_face_stream, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.fr_face_stream, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(256, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.fr_face_container, 1, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.bt_train = QtGui.QPushButton(self.c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_train.sizePolicy().hasHeightForWidth())
        self.bt_train.setSizePolicy(sizePolicy)
        self.bt_train.setObjectName("bt_train")
        self.gridLayout.addWidget(self.bt_train, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.fr_top = QtGui.QFrame(self.c)
        self.fr_top.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_top.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_top.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_top.setObjectName("fr_top")
        self.gridLayout_4 = QtGui.QGridLayout(self.fr_top)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtGui.QSpacerItem(632, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.lb_status = QtGui.QLabel(self.fr_top)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.lb_status.setFont(font)
        self.lb_status.setObjectName("lb_status")
        self.gridLayout_4.addWidget(self.lb_status, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(632, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.fr_top, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.c)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_train.setText(QtGui.QApplication.translate("MainWindow", "Take Train", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_status.setText(QtGui.QApplication.translate("MainWindow", "Hai", None, QtGui.QApplication.UnicodeUTF8))

